#!/bin/bash

: '
uasr: wbmins
mail: wbminions@gmail.com
desc: a convenient git for hugo shell
'

: '
desc: commit and push
args: commit msg
'

push() {
    git add .
    git commit -m "$1"
    git push -u origin master
}


: '
desc: hugo localhost
args: none
'
server() {
    hugo server -D
}

: '
desc: created a hugo blog
args: filename
'
new() {
    while true; do
        file_num=`echo ${num}|awk '{printf("%03d\n", $0)}'`
        file="/home/pluto/github/Hugo/content/posts/${file_num}.md"
        if test -f $file; then
            let num+=1
        else
            hugo new posts/${file_num}.md
            break
        fi
    done
}

if [ ! -z "$1" ]; then
    if [ "$1" == "push" ]; then
        push "$2"
    fi
    if [ "$1" == "new" ]; then
        new
    fi
    [ "$1" == "server" ] && server
fi