#!/bin/bash

: '
auther: wbmins
email: wbminions@gmail.com
description: a convenient git and hugo shell
'

push() {
    git add .
    git commit -m "$1"
    git push -u origin master
}

server() {
    hugo server -D
}

new() {
    hugo new posts/$1.md
}

if [ ! -z "$1" ]; then
    if [ "$1" == "push" ]; then
        push "$2"
    fi
    if [ "$1" == "new" ]; then
        new "$2"
    fi
    [ "$1" == "server" ] && server
fi