name: build & deploy
on:
  push:
    branches:
    # 你的hugo源码分支
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      # 如果使用了git submodules
      with:
        submodules: true
        fetch-depth: 1

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.59.1'
        # extended: true

    - name: Build
      uses: jakejarvis/hugo-build-action@master

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action
      with:
        GH_EMAIL: wbminions@gmail.com
        GH_USERNAME: wbmins
        GH_REPO: github.com/wbmins/wbmins.github.io
        GH_BRANCH: master
        GH_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        WORK_DIR: "./public"