name: build
on:
  push: # push的时候触发
    branches: # 那些分支需要触发
      - master

jobs:
  checkout-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
          submodules: true
          fetch-depth: 1
    steps:
    - name: Build site
      uses: jakejarvis/hugo-build-action@master
    
  deploy:
    needs: checkout-build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      uses: wbmins/Push-Github-Pages@master
      with:
        GH_EMAIL: wbminions@gmail.com
        GH_USERNAME: wbmins
        GH_REPO: github.com/wbmins/wbmins.github.io
        GH_BRANCH: master
        GH_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        WORK_DIR: "./public"
