name: Build & Deploy
on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
          submodules: true
          fetch-depth: 1

    - name: Build site
      uses: jakejarvis/hugo-build-action@master

    - name: Deploy to GitHub
      uses: wbmins/git-push@master

      with:
        GH_EMAIL: 1358258634@qq.com
        GH_USERNAME: wbmins
        GH_REPO: github.com/wbmins/wbmins.github.io
        GH_BRANCH: master
        GH_TOKEN: ${{ ACTIONS_DEPLOY_KEY }}
        WORK_DIR: "./public"